name: wajbah_chef
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  iconify_flutter: ^0.0.5
  flutter_native_splash: ^2.3.8
  image_picker: ^1.0.7
  device_preview: ^1.1.0
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.67.0
  dio: ^5.4.3+1
  dartz:
  flutter_bloc: ^8.1.5 
  webview_flutter: ^3.0.0
  webview_windows: 




flutter_native_splash:
  android: true
  ios: true
  web: false

  image: assets/images/Wajbah_Finale.png
  color: "#4E68FB"
  android_12:
    image: assets/images/Wajbah_Finale.png
    color: "#4E68FB"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/images/menu/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Black.ttf
          weight: 900
        - asset: assets/fonts/Biryani-Bold.ttf
          weight: 700
        - asset: assets/fonts/Biryani-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Biryani-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Biryani-Light.ttf
          weight: 300
        - asset: assets/fonts/Biryani-Regular.ttf
          weight: 400
        - asset: assets/fonts/Biryani-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
